name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:    
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up P  ython ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Postgres
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '13'
        postgresql db: 'demo'
        postgresql user: 'postgres'
        postgresql password: 'postgres'
    - name: Run Tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: ${{ secrets.DEBUG }}
        PG_USER: 'postgres'
        PG_PASSWORD: 'postgres'
        PG_DB_NAME: 'demo'
        PG_HOST: '127.0.0.1'
        PG_PORT: 5432
      run: |
        cd book_shop/
        python manage.py migrate
        python manage.py load_data
        python manage.py test
