name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    
    services: 
      postgres:
          # Docker Hub image
          image: postgres
          env:
            POSTGRES_PASSWORD: ${{ secrets.PG_PASSWORD }}
            POSTGRES_USER: ${{ secrets.PG_USER }}
            POSTGRES_DB: ${{ secrets.PG_DB_NAME }}
          ports:
            - 5432:5432
    
    
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]



    steps:
    - uses: actions/checkout@v2
    - name: Set up P  ython ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create, populate & query PostgreSQL
      uses: Oxfos/action-postgres-setup@v1
    - name: Run Tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: ${{ secrets.DEBUG }}
        PG_USER: ${{ secrets.PG_USER }}
        PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
        PG_DB_NAME: ${{ secrets.PG_DB_NAME }}
        PG_HOST: ${{ secrets.PG_HOST }}
        PG_PORT: ${{ secrets.PG_PORT }}
      run: |
        cd book_shop/
        python manage.py test
